from .model import *
from .utils import datetime_decoder
from .utils import discriminator_decoder
from dataclasses import dataclass
from dataclasses import field
from datetime import date
from datetime import datetime
from datetime import time
from enum import Enum
from http_server_base.auth import *
from http_server_base.model.filtering_json_encoder import FilteringJsonEncoder
from http_server_base.model.iencoder import IEncoder
from http_server_base.tools.filters import filter_out_smart
from http_server_base.tools.logging import RequestLogger
from http_server_base.tools.subrequest_classes import HttpSubrequest
from tornado.httpclient import HTTPRequest
from typing import *
from urllib.parse import ParseResult
from urllib.parse import urlparse
from lib.oauth2 import OAuth2AuthProvider

class LockStatusApiClientServers(Enum):
    """ Enum-container of default servers used for `LockStatusApiClient` """
    
    HttpsApiMercedesBenzComVehicledataV2 = 'https://api.mercedes-benz.com/vehicledata/v2'

class LockStatusApiClient(AuthorizedClient):
    """
    This API allows access to vehicle lock status data of Mercedes-Benz vehicles remotely.
    
    Data is categorized into resources and containers for the polling interface. They are defined
    as follows:
    
    * *Resource*: A resource is a single information about a vehicle. It's a measurement that
    consists of a name (also referred to as resource ID), a value, and an associated timestamp. See
    below for a list and description of all resources that this API provides.
    
    * *Container*: A container is a set of resources that are defined to group data for a certain
    use case.
    
    The interface is a ISO 20078-compliant REST endpoint to query the latest data for a vehicle. If
    the vehicle did not send an update for a resource within 12 hours, the response will be empty.
    
    ## Resources
    
    This is an alphabetical list of all resources that the API provides.
    
    Name | Description | Unit/Range
    
    ---- | ----------- | ----------
    
    doorlockstatusdecklid | Lock status of the deck lid | false: locked<br>true: unlocked
    
    doorlockstatusvehicle | Vehicle lock status | 0: vehicle unlocked<br>1: vehicle internal
    locked<br>2: vehicle external locked<br>3: vehicle selective unlocked
    
    doorlockstatusgas | Status of gas tank door lock | false: locked<br>true: unlocked
    
    positionHeading | Vehicle heading position | 0..359.9 degrees
    
    Meta:
         - Generated by Python OpenAPI Parser
    """
    
    server: Union[LockStatusApiClientServers, str]
    logger_name: str = 'LockStatus.client'
    model_encoder: Type[IEncoder] = FilteringJsonEncoder
    
    def __init__(self, server: Union[LockStatusApiClientServers, str] = LockStatusApiClientServers.HttpsApiMercedesBenzComVehicledataV2):
        if (isinstance(server, LockStatusApiClientServers)):
            server = server.value
        
        super().__init__()
        self.server = server
        self.initialize_logger()
        self.logger = RequestLogger(None, self.logger)
        
    
    # region Utility Methods
    async def _fetch__form_request(self, request: Union[str, HTTPRequest, HttpSubrequest], **kwargs) -> HttpSubrequest:
        request = await super()._fetch__form_request(request, **kwargs)
        request = await self._fetch__form_request__add_server(request)
        return request
    
    async def _fetch__form_request__add_server(self, request: HttpSubrequest) -> HttpSubrequest:
        parsed: ParseResult = urlparse(request.url)
        if (not parsed.hostname):
            request.url = self.server + request.url
        
        return request
    
    # endregion
    # region Authorization Methods
    async def provide_o_auth2_authorization(self, scopes, redirect_uri, client_id, client_secret):
        provider = OAuth2AuthProvider(
            auth_service='https://id.mercedes-benz.com/as/authorization.oauth2',
            token_service='https://id.mercedes-benz.com/as/token.oauth2',
            client_id=client_id,
            client_secret=client_secret,
            redirect_uri=redirect_uri,
            scopes=scopes
        )

        return provider
    # async def provide_o_auth2_authorization \
    # (
    #     self,
    #     state: str = None,
    #     redirect_uri: str = None,
    #     *,
    #     client_id: Optional[str] = None,
    #     client_secret: Optional[str] = None,
    #     scope: Optional[List[str]] = None,
    # ) -> OAuth2AuthorizationProvider:
    #     provider = OAuth2AuthorizationProvider(client_id=client_id, client_secret=client_secret, redirect_uri=redirect_uri, token_url='https://id.mercedes-benz.com/as/token.oauth2', authorization_url='https://id.mercedes-benz.com/as/authorization.oauth2', refresh_url=None)
    #     await provider.authorize_via_redirect_uri(state=state, scope=scope)
    #     return provider
    
    # endregion
    # region Client Methods
    async def get_resources_for_container_id_using_ge_t(self, vehicle_id: str, access_token: str) -> List[VehicleLockStatus]:
        """
        Returns all resources for the container 'vehiclelockstatus', data can be filtered for a certain
        time range.
        
        Arguments:
            vehicle_id: `str`.
                **REQUIRED.** Vehicle identification number
        
        Returns:
            `List[VehicleLockStatus]`. OK
        
        Generated by Python OpenAPI Parser
        """
        
        _, resp = await self.fetch_json \
        (
            request = f'/vehicles/{vehicle_id}/containers/vehiclelockstatus',
            expected_content_type = 'application/json;charset=utf-8',
            access_token=access_token,
            expected_codes = [ 200 ],
        )
        return resp
    
    async def get_all_resources_for_vin_using_ge_t(self, vehicle_id: str, access_token: str) -> List[ResourceMetaInfo]:
        """
        Returns all available resources for the provided vehicle identification number.
        
        Arguments:
            vehicle_id: `str`.
                **REQUIRED.** Vehicle identification number
        
        Returns:
            `List[ResourceMetaInfo]`. OK
        
        Generated by Python OpenAPI Parser
        """
        
        _, resp = await self.fetch_json(request=f'/vehicles/{vehicle_id}/resources', expected_content_type='application/json;charset=utf-8', access_token=access_token ,expected_codes=[ 200 ])
        return resp
    
    async def get_latest_door_lock_statusdeck_lid_using_ge_t(self, vehicle_id: str) -> GetLatestDoorLockStatusdeckLidUsingGETResponse:
        """
        Returns the latest available door lock deck lid status resource for the provided vehicle
        identification number.
        
        Arguments:
            vehicle_id: `str`.
                **REQUIRED.** Vehicle identification number
        
        Returns:
            `GetLatestDoorLockStatusdeckLidUsingGETResponse`. OK
        
        Generated by Python OpenAPI Parser
        """
        
        _, resp = await self.fetch_json_model \
        (
            request = f'/vehicles/{vehicle_id}/resources/doorlockstatusdecklid',
            model = GetLatestDoorLockStatusdeckLidUsingGETResponse,
            expected_content_type = 'application/json;charset=utf-8',
            expected_codes = [ 200 ],
        )
        return resp
    
    async def get_latest_door_lock_status_gas_using_ge_t(self, vehicle_id: str) -> GetLatestDoorLockStatusGasUsingGETResponse:
        """
        Returns the latest available door lock status gas resource for the provided vehicle
        identification number.
        
        Arguments:
            vehicle_id: `str`.
                **REQUIRED.** Vehicle identification number
        
        Returns:
            `GetLatestDoorLockStatusGasUsingGETResponse`. OK
        
        Generated by Python OpenAPI Parser
        """
        
        _, resp = await self.fetch_json_model \
        (
            request = f'/vehicles/{vehicle_id}/resources/doorlockstatusgas',
            model = GetLatestDoorLockStatusGasUsingGETResponse,
            expected_content_type = 'application/json;charset=utf-8',
            expected_codes = [ 200 ],
        )
        return resp
    
    async def get_latest_door_lock_status_using_ge_t(self, vehicle_id: str) -> GetLatestDoorLockStatusUsingGETResponse:
        """
        Returns the latest available door lock status resource for the provided vehicle identification
        number.
        
        Arguments:
            vehicle_id: `str`.
                **REQUIRED.** Vehicle identification number
        
        Returns:
            `GetLatestDoorLockStatusUsingGETResponse`. OK
        
        Generated by Python OpenAPI Parser
        """
        
        _, resp = await self.fetch_json_model \
        (
            request = f'/vehicles/{vehicle_id}/resources/doorlockstatusvehicle',
            model = GetLatestDoorLockStatusUsingGETResponse,
            expected_content_type = 'application/json;charset=utf-8',
            expected_codes = [ 200 ],
        )
        return resp
    
    async def get_latest_position_heading_using_ge_t(self, vehicle_id: str) -> GetLatestPositionHeadingUsingGETResponse:
        """
        Returns the latest available position heading resource for the provided vehicle identification
        number.
        
        Arguments:
            vehicle_id: `str`.
                **REQUIRED.** Vehicle identification number
        
        Returns:
            `GetLatestPositionHeadingUsingGETResponse`. OK
        
        Generated by Python OpenAPI Parser
        """
        
        _, resp = await self.fetch_json_model \
        (
            request = f'/vehicles/{vehicle_id}/resources/positionHeading',
            model = GetLatestPositionHeadingUsingGETResponse,
            expected_content_type = 'application/json;charset=utf-8',
            expected_codes = [ 200 ],
        )
        return resp
    
    # endregion
    

__all__ = \
[
    'LockStatusApiClient',
    'LockStatusApiClientServers',
]
